name: banwet
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
 
  get:
  im_stepper: ^1.0.1+1
  animated_splash_screen: ^1.3.0
  card_swiper: ^3.0.1
  curved_navigation_bar: ^1.0.3
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  get_storage: ^2.0.3
  flutter_typeahead: ^4.1.1
  geolocator:
  geocoding:
  firebase_core: ^2.4.1
  flutter_bloc: ^8.1.3

  firebase_messaging:
  cached_network_image: ^3.3.0
  dotted_decoration: ^2.0.0

  flutter_spinkit: ^5.1.0
  sizer: ^2.0.15
  flutter_staggered_animations: ^1.1.1
  dropdown_button2: ^2.3.9
  searchfield: ^0.8.4
  date_time_picker: ^2.1.0
  json_serializable: ^6.7.1
  dropdown_search: ^6.0.1
  image_picker: ^1.0.4
  fluttertoast: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^6.1.0
  flutter_cache_manager: ^3.3.1
  blurhash_dart: ^1.2.1
  flutter_blurhash: ^0.7.0
  flutter_image_compress: ^2.1.0
  pinput: ^5.0.0
  syncfusion_flutter_datepicker: ^21.2.3
  flutter_switch: ^0.3.2
  calendar_date_picker2: ^1.1.5
  date_picker_plus: ^4.1.0
  version_check: ^0.7.1
  package_info_plus: ^5.0.1
  url_launcher: ^6.3.0
  image_picker_ios: ^0.8.12
  path_provider: ^2.1.4
  path: ^1.9.0
  percent_indicator: ^4.2.3
  intl: ^0.17.0
  multi_dropdown: ^3.0.1
  # html_editor_enhanced: 
  # html_editor_enhanced: ^2.5.1

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  injectable_generator: ^1.5.3
  build_runner: ^2.4.5  

  flutter_lints: ^2.0.0
  flutter_quill: ^7.3.2
  


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/ca/
    - assets/svg/
  

  fonts:
    - family: Poppins-Light
      fonts:
        - asset: fonts/Poppins-Light.ttf
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: fonts\Poppins-Medium.ttf  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
